[customizations.kernel]
append = "quiet loglevel=3 systemd.show_status=auto rd.udev.log_level=3"

[customizations.installer.kickstart]
contents = """
text --non-interactive
lang en_US.UTF-8
keyboard --vckeymap=dk --xlayouts=dk
timezone Europe/Copenhagen --utc

network --bootproto=dhcp --device=link --activate --onboot=on

rootpw --lock
user --name=nix --password=password --plaintext --groups=wheel
sshkey --username=nix "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE0KRfd6Xm3aRKRKVbqoWDIgN8Y8LvD/DdozE3cPzlZ/"

zerombr
clearpart --all --initlabel --disklabel=gpt

part /boot/efi --fstype=efi --size=600
part /boot --fstype=ext4 --size=1024
part pv.01 --grow --size=1

volgroup vg0 pv.01
logvol / --vgname=vg0 --name=root --fstype=xfs --grow --size=10240

reboot --eject
"""
